### PR TITLE
Extend schedule output to provide both metadata and schedule

### LINKED ISSUE #21: Extend the schedule output to provide a summary and details
There are good reasons to return additional information (i.e. metadata) together with the schedule request. In fact there could be the following cases:
1. Return metadata + schedule data
2. Return metadata only (since a full schedule can be very big)
3. Return schedule data only (because this eventually makes it easier to handle the response for clients that can easier deal with an iCal document alone, for example the iCal document of a single job, see #19 )

How the schedule request response would look like can be set through parameters with the default set to `1.`?

What information could be "metadata":
- response code
- human readable response code description
- request statistics 
- schedule statistics/summaries
- unassigned job/shipments (if any)
- scheduling parameters used
- other interesting stuff

Vroom Express for example does this: https://github.com/VROOM-Project/vroom/blob/master/docs/API.md#output

### PR DESCRIPTION
**Pull request by krashish8**
Fixes #21.

Changes proposed in this pull request:
- Extend the schedule output to provide metadata and the complete schedule, using optional "overview" query parameter.
  - When `?overview=true` is used as query parameter in the URL, then only metadata is returned.
  - Else both metadata and schedule is returned.
  - Metadata includes the summary of each vehicle, unassigned jobs, and the summary of complete problem.
- Also extended all API responses to provide message and status code.
- Returning 404 NotFound Error instead of empty list when the project/task id is wrong.

### CODE REVIEW

**Comment by dkastl** [comment]
Just thought what would be returned with `?overview=false`? Does this make sense?
Would `?overview=false` maybe return only the schedule?

**Comment by krashish8** [comment]
No, `?overview=false` (or `overview=anythingelse`) will return both the schedule and the metadata. It actually depends on us on what to do, so any suggestions (or better naming ideas) are welcome :-)

I have used the HTTP Content-Type header to decide on whether to return the iCal document or the JSON response.

image

So, there are actually three ways to get the schedule using the same endpoint (say `GET /projects/{project_id}/schedule`):
1. **Content-Type is text/calendar**: This will return only the schedule irrespective of any query parameter (with perhaps the template provided, in the future), because normally only the schedule is expected on the iCal document.
2. **Content-Type is application/json, and overview=true**: This will return a JSON response with only the metadata field - each vehicle summary, full summary, unallocated tasks (everything except the schedule, because a full schedule can be very big).
3. **Content-Type is application/json, and overview=false or anythingelse or no overview**: This will return a JSON response with both metadata field and schedule field. I feel that if someone wants a JSON response of the schedule, then there should not be an issue in giving back small metadata information too with the response.

**Comment by dkastl** [comment]
Oh, the content type is a nice idea!

Regarding `overview` parameter, this was just what came to my mind when I saw this pull request.

My first thought was that the meaning of `overview=true` and what the user receives could be misunderstood. What about these ideas:

## `show` parameter 

Add something like 
* `?show=overview` -> only includes the "metadata"
* `?show=schedule` -> only includes the "schedule"
* Without `show` parameter both are retruned

Alterative parameter names could be `display` or `include` or `filter` for example.

## `schedule` and `overview` parameters

We could have two parameters to turn on/off the display of `schedule` and `overview`. 
* `?overview=true|false`
* `?schedule=true|false`

If the parameter is not provided, then the assumption would be `true`. Or in other words, providing one of them would turn off the output.

**Comment by krashish8** [comment]
The first idea looks good to me and it will be simple enough for the user to give a single `show` parameter to decide on which field to return.

Two parameters for doing this might be confusing to the user or overkill. Btw, the "true" and "false" don't add any semantic value, because the query parameters are just key-value pairs of "strings". So, true/false are actually strings and not boolean.

**Comment by dkastl** [comment]
I see. I wasn't sure if they were boolean and needed. I also like more the first idea.

In case there would be more things to hide and show, it could be also extended then in the future to something like `?show=overview,schedule` to provide a list of keywords.

**Comment by dkastl** [comment]
Would it make sense to not use `show` but `hide`? This would make it more obvious that not providing the parameter would show all.

**Comment by dkastl** [comment]
A third possibility could be to name the parameter `output` and the value could be something like:

* `?output=schedule`
* `?output=overview`

but there could be also something like

* `?output=basic`
* `?output=verbose`
* `?output=debug`

**Comment by krashish8** [comment]
Maybe, we could use `?fields=overview`, `?fields=schedule` which can be later generalized to all other endpoints to get a partial response, such as `?fields=overview,schedule`. And we can mention that by default if nothing is specified, then all the fields are returned.

**Comment by dkastl** [comment]
`fields` sounds good.

**Pull request merged**
